os:
    - linux
services:
    - docker
language: node_js
node_js:
    - "10.13.0"
sudo: false
cache:
    directories:
        - node
        - node_modules
env:
    global:
        - NODE_VERSION=10.13.0
before_install:
    - nvm install $NODE_VERSION
    - npm install -g npm
    - node -v
    - npm -v
install:
    - npm install
script:
    - grunt eslint
notifications:
    webhooks:
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: false     # default: false
