# To Do:
# Add working directory

version: "3"

services:
    mongodb:
        image: mongo:4.0.2
        container_name: mongodb
        ports:
            - "27017:27017"
        volumes:
            - ~/volumes/dega/mongodb/:/data/db/
